name: Sync With Upstream

on: [push]

jobs:
    sync_with_upstream:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v4
              with:
                  python-version: '3.10'
            - run: python scripts/sync_with_upstream.py -d
            - run: echo $?
            - run: echo 'Done!'
