name: Sync With Upstream

on: [push]

jobs:
    sync_with_upstream:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v4
              with:
                  python-version: '3.10'
            - run: |
                python scripts/sync_with_upstream.py -d
            - name: Get Previous Tag
              id: prev_tag
              if: failure()
              run: |
                  PREV_TAG=$(<rembg-commit-ref)
                  echo "::set-output name=baseRef::$PREV_TAG"
            - name: Generate Changelog
              id: generate_changelog
              if: success()
              uses: nblagoev/pull-release-notes-action@v1.0.2
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  base-ref: ${{ steps.prev_tag.outputs.baseRef }}
                  head-ref: ${{ github.ref }}
                  repository: danielgatis/rembg
            - if: success()
              run: |
                  echo ${{steps.generate_changelog.outputs.result}}

#            - name: Create Release
#              uses: actions/create-release@v1
#              env:
#                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#              with:
#                  tag_name: ${{ github.ref }}
#                  release_name: Release ${{ github.ref }}
#                  body: ${{steps.generate_changelog.outputs.result}}
#                  draft: true
