name: Sync With Upstream

on: [push]

jobs:
    sync_with_upstream:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v4
              with:
                  python-version: '3.10'
            - id: sync
              run: |
                  python scripts/sync_with_upstream.py -d
            - name: Set Outputs
              id: so
              run: |
                  PREV_TAG=$(<rembg-commit-ref)
                  CURR_TAG=$(<rembg-upstream/.git/refs/heads/main)
                  echo "$CURR_TAG" > rembg-commit-ref
                  echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
                  echo "baseRef=$PREV_TAG" >> $GITHUB_OUTPUT
                  echo "headRef=$CURR_TAG" >> $GITHUB_OUTPUT
            - name: Generate Changelog
              id: generate_changelog
              uses: nblagoev/pull-release-notes-action@v1.0.2
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  base-ref: ${{ steps.so.outputs.baseRef }}
                  head-ref: ${{ steps.so.outputs.headRef }}
                  repository: danielgatis/rembg
            - name: Create Pull Request
              uses: peter-evans/create-pull-request@v4
              commit-message: [create-pull-request] Changes Detected in Upstream
              branch: create-pull-request/auto-updates-${{ steps.so.outputs.date }}
              delete-branch: true
              title: [${{ steps.so.outputs.date }}] Changes Detected in Upstream
              body: ${{steps.generate_changelog.outputs.result}}
              reviewers: rnag
