name: Test installation

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.8", "3.9", "3.10"]

        steps:
            - uses: actions/checkout@v3
# disabling for now, because I easily hit bandwidth issues this way.
# see also:
#   https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-storage-and-bandwidth-usage
#              with:
#                  lfs: 'true'
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Install package
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements-dev.txt
                  (echo "import pooch" ; \
                   echo "url = 'https://github.com/danielgatis/rembg/releases/download/v0.0.0/u2net.onnx'"; \
                   echo "md5 = '60024c5c889badc19c04ad937298a77b'"; \
                   echo "fname = url.rsplit('/', 1)[1]"; \
                   echo "pooch.retrieve(url, f'md5:{md5}', fname=fname, path='./rembg', progressbar=True)") \
                  | python
                  chmod 777 ./rembg/*.onnx
                  pip install .
            - name: Test installation with pytest
              run: |
                  pytest
